var annotated =
[
    [ "AST", "class_a_s_t.html", "class_a_s_t" ],
    [ "ASTNode", "class_a_s_t_node.html", "class_a_s_t_node" ],
    [ "Calls", "class_calls.html", "class_calls" ],
    [ "CFG", "class_c_f_g.html", "class_c_f_g" ],
    [ "CFGNode", "class_c_f_g_node.html", "class_c_f_g_node" ],
    [ "Design", "class_design.html", null ],
    [ "DesignExtractor", "class_design_extractor.html", "class_design_extractor" ],
    [ "Follows", "class_follows.html", "class_follows" ],
    [ "Modifies", "class_modifies.html", "class_modifies" ],
    [ "ModifiesP", "class_modifies_p.html", "class_modifies_p" ],
    [ "Next", "class_next.html", "class_next" ],
    [ "Parent", "class_parent.html", "class_parent" ],
    [ "Parser", "class_parser.html", "class_parser" ],
    [ "PKB", "class_p_k_b.html", null ],
    [ "PKBController", "class_p_k_b_controller.html", "class_p_k_b_controller" ],
    [ "ProcTable", "class_proc_table.html", "class_proc_table" ],
    [ "QueryClause", "class_query_clause.html", "class_query_clause" ],
    [ "QueryEvaluator", "class_query_evaluator.html", "class_query_evaluator" ],
    [ "QueryPreprocessor", "class_query_preprocessor.html", "class_query_preprocessor" ],
    [ "QueryPreprocessorDebug", "class_query_preprocessor_debug.html", "class_query_preprocessor_debug" ],
    [ "QueryProcessor", "class_query_processor.html", "class_query_processor" ],
    [ "QueryTarget", "class_query_target.html", "class_query_target" ],
    [ "QueryValidator", "class_query_validator.html", "class_query_validator" ],
    [ "QueryVariable", "class_query_variable.html", "class_query_variable" ],
    [ "stmtDetail", "structstmt_detail.html", "structstmt_detail" ],
    [ "Uses", "class_uses.html", "class_uses" ],
    [ "UsesP", "class_uses_p.html", "class_uses_p" ],
    [ "VarTable", "class_var_table.html", "class_var_table" ]
];